package com.inmar.skudatamanagement.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.io.Serializable;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "SKU_TABLE")
public class LocationEntity implements Serializable {
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
//    @GeneratedValue
//    @Column(columnDefinition = "id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL PRIMARY KEY")
//    @Column(columnDefinition = "bigint not null constraint user_pkey primary key")
    private Integer skuId;

    @Column
    private String skuName;
    @Column
    private String location;
    @Column
    private String department;
    @Column
    private String category;
    @Column
    private String subCategory;

}
