spring:
#  datasource:
#    url: jdbc:h2:mem:skudb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
  h2:
    console:
      enabled: true
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect

cred:
  username: admin
  password: admin
